-- 0002_core_tables.sql
--
-- Core tables. Design decisions that are load-bearing:
--
--  * UUID primary keys (`gen_random_uuid()`), so ids can be generated by the
--    client of the database without a round trip and never leak row order.
--  * `timestamptz` everywhere, defaulted to `now()`; the API serialises UTC.
--  * Published versions are immutable: `resource_versions` rows are only ever
--    inserted, and `resource_files` cascade from them.
--  * `resources.latest_version_id` is the canonical pointer to the current
--    version. It is nullable because a draft has no version yet, and it is
--    maintained by the publishing function, never by the client.
--  * Deletion of published resources is soft (`deleted_at`); version history is
--    preserved.

-- ---------------------------------------------------------------------------
-- Identity
-- ---------------------------------------------------------------------------

-- Mirrors Supabase Auth's user table. Rows are created by a trigger on signup
-- (see 0004) or by the API using the service role.
create table if not exists users (
  id            uuid primary key default gen_random_uuid(),
  email         citext not null unique,
  is_banned     boolean not null default false,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  last_seen_at  timestamptz
);

create table if not exists profiles (
  user_id         uuid primary key references users (id) on delete cascade,
  username        citext not null unique,
  display_name    text,
  bio             text,
  avatar_url      text,
  website_url     text,
  github_username citext,
  role            user_role not null default 'user',
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  constraint profiles_username_format check (username ~ '^[a-z0-9](?:[a-z0-9-]{1,38})[a-z0-9]$'),
  constraint profiles_bio_length check (bio is null or char_length(bio) <= 400)
);

-- ---------------------------------------------------------------------------
-- Reference data
-- ---------------------------------------------------------------------------

create table if not exists licenses (
  id           uuid primary key default gen_random_uuid(),
  spdx_id      citext not null unique,
  name         text not null,
  url          text,
  osi_approved boolean not null default false,
  created_at   timestamptz not null default now()
);

create table if not exists categories (
  id            uuid primary key default gen_random_uuid(),
  slug          citext not null unique,
  name          text not null,
  description   text,
  resource_type resource_type,
  sort_order    integer not null default 0,
  created_at    timestamptz not null default now()
);

create table if not exists tags (
  id         uuid primary key default gen_random_uuid(),
  slug       citext not null unique,
  name       text not null,
  created_at timestamptz not null default now(),
  constraint tags_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

-- ---------------------------------------------------------------------------
-- Design systems: the persistent identity a resource inherits
-- ---------------------------------------------------------------------------

create table if not exists design_systems (
  id                  uuid primary key default gen_random_uuid(),
  slug                citext not null unique,
  name                text not null,
  description         text,
  genre               design_genre,
  macrostructure      macrostructure,
  density             density,
  shape_language      shape_language,
  motion_language     motion_language,
  typography_style    typography_style,
  color_strategy      color_strategy,
  -- The `design.md` source, stored verbatim so AI consumers and the CLI can
  -- read exactly what the author wrote.
  design_md           text,
  repository_url      text,
  preview_url         text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  deleted_at          timestamptz
);

create table if not exists design_tokens (
  id               uuid primary key default gen_random_uuid(),
  design_system_id uuid not null references design_systems (id) on delete cascade,
  token_type       design_token_type not null,
  name             text not null,
  value            text not null,
  dark_value       text,
  description      text,
  sort_order       integer not null default 0,
  created_at       timestamptz not null default now(),
  constraint design_tokens_unique_name unique (design_system_id, token_type, name)
);

-- ---------------------------------------------------------------------------
-- Resources
-- ---------------------------------------------------------------------------

create table if not exists resources (
  id                uuid primary key default gen_random_uuid(),
  slug              citext not null unique,
  -- Registry namespace the resource is published under. Names are globally
  -- unique, so the namespace is a routing concern, not a scope.
  namespace         citext not null default 'default',
  name              text not null,
  title             text not null,
  description       text not null,
  resource_type     resource_type not null,
  status            resource_status not null default 'draft',
  category_id       uuid references categories (id) on delete set null,
  design_system_id  uuid references design_systems (id) on delete set null,
  license_id        uuid references licenses (id) on delete set null,
  author_id         uuid references profiles (user_id) on delete set null,
  -- Maintained by app.publish_resource(); never written directly by clients.
  latest_version_id uuid,
  repository_url    text,
  documentation_url text,
  preview_url       text,
  difficulty        difficulty,
  download_count    integer not null default 0,
  view_count        integer not null default 0,
  favorite_count    integer not null default 0,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  published_at      timestamptz,
  deleted_at        timestamptz,
  constraint resources_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint resources_description_length check (char_length(description) between 20 and 320),
  constraint resources_title_length check (char_length(title) between 2 and 80),
  constraint resources_counters_non_negative check (
    download_count >= 0 and view_count >= 0 and favorite_count >= 0
  ),
  -- A resource can only be published with a version attached.
  constraint resources_published_requires_version check (
    status <> 'published' or latest_version_id is not null
  )
);

create table if not exists resource_versions (
  id           uuid primary key default gen_random_uuid(),
  resource_id  uuid not null references resources (id) on delete cascade,
  version      text not null,
  commit_sha   text,
  changelog    text,
  integrity    text,
  -- Dependency metadata is recorded on the version, not derived from files:
  -- a version's dependency set is part of what was reviewed and published.
  npm_dependencies      text[] not null default '{}',
  registry_dependencies text[] not null default '{}',
  is_latest    boolean not null default false,
  created_at   timestamptz not null default now(),
  published_at timestamptz,
  constraint resource_versions_semver check (version ~ '^[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z.-]+)?$'),
  constraint resource_versions_unique unique (resource_id, version)
);

-- `latest_version_id` points at a version that must belong to the resource.
alter table resources
  drop constraint if exists resources_latest_version_fk;
alter table resources
  add constraint resources_latest_version_fk
  foreign key (latest_version_id) references resource_versions (id) on delete set null;

create table if not exists resource_files (
  id                  uuid primary key default gen_random_uuid(),
  resource_version_id uuid not null references resource_versions (id) on delete cascade,
  path                text not null,
  file_type           text not null,
  target              text,
  content             text not null,
  content_hash        text not null,
  size_bytes          integer not null default 0,
  source_url          text,
  created_at          timestamptz not null default now(),
  constraint resource_files_unique_path unique (resource_version_id, path),
  -- Path safety is enforced in the database as well as in the validator: a
  -- traversal segment must never reach a row, let alone a filesystem.
  constraint resource_files_path_safe check (
    path !~ '(^|/)\.\.(/|$)' and path !~ '\\' and path !~ '^/' and position(chr(0) in path) = 0
  ),
  constraint resource_files_size_non_negative check (size_bytes >= 0)
);

create table if not exists resource_tags (
  resource_id uuid not null references resources (id) on delete cascade,
  tag_id      uuid not null references tags (id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (resource_id, tag_id)
);

-- ---------------------------------------------------------------------------
-- Community
-- ---------------------------------------------------------------------------

create table if not exists collections (
  id          uuid primary key default gen_random_uuid(),
  owner_id    uuid not null references profiles (user_id) on delete cascade,
  slug        citext not null,
  title       text not null,
  description text,
  is_public   boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  constraint collections_owner_slug_unique unique (owner_id, slug)
);

create table if not exists collection_items (
  id            uuid primary key default gen_random_uuid(),
  collection_id uuid not null references collections (id) on delete cascade,
  resource_id   uuid not null references resources (id) on delete cascade,
  note          text,
  sort_order    integer not null default 0,
  created_at    timestamptz not null default now(),
  constraint collection_items_unique unique (collection_id, resource_id)
);

create table if not exists favorites (
  user_id     uuid not null references profiles (user_id) on delete cascade,
  resource_id uuid not null references resources (id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (user_id, resource_id)
);

create table if not exists downloads (
  id                  uuid primary key default gen_random_uuid(),
  resource_id         uuid not null references resources (id) on delete cascade,
  resource_version_id uuid references resource_versions (id) on delete set null,
  user_id             uuid references profiles (user_id) on delete set null,
  -- Salted digest of the client address. Raw addresses are never stored.
  client_hash         text,
  occurred_at         timestamptz not null default now()
);

create table if not exists views (
  id          uuid primary key default gen_random_uuid(),
  resource_id uuid not null references resources (id) on delete cascade,
  user_id     uuid references profiles (user_id) on delete set null,
  client_hash text,
  day         date not null default current_date,
  viewed_at   timestamptz not null default now()
);

create table if not exists contributors (
  id              uuid primary key default gen_random_uuid(),
  profile_user_id uuid unique references profiles (user_id) on delete set null,
  github_username citext unique,
  name            text not null,
  avatar_url      text,
  bio             text,
  created_at      timestamptz not null default now()
);

create table if not exists resource_contributors (
  resource_id    uuid not null references resources (id) on delete cascade,
  contributor_id uuid not null references contributors (id) on delete cascade,
  role           contributor_role not null default 'author',
  primary key (resource_id, contributor_id, role)
);

-- ---------------------------------------------------------------------------
-- Moderation
-- ---------------------------------------------------------------------------

create table if not exists submissions (
  id               uuid primary key default gen_random_uuid(),
  submitter_id     uuid references profiles (user_id) on delete set null,
  resource_id      uuid references resources (id) on delete set null,
  slug             citext not null,
  title            text not null,
  description      text not null,
  resource_type    resource_type not null,
  status           submission_status not null default 'pending',
  pull_request_url text,
  review_notes     text,
  reviewer_id      uuid references profiles (user_id) on delete set null,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  constraint submissions_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

create table if not exists reviews (
  id            uuid primary key default gen_random_uuid(),
  submission_id uuid not null references submissions (id) on delete cascade,
  reviewer_id   uuid not null references profiles (user_id) on delete cascade,
  decision      submission_status not null,
  notes         text,
  created_at    timestamptz not null default now(),
  constraint reviews_one_per_reviewer unique (submission_id, reviewer_id)
);

create table if not exists reports (
  id               uuid primary key default gen_random_uuid(),
  resource_id      uuid references resources (id) on delete cascade,
  reporter_id      uuid references profiles (user_id) on delete set null,
  reason           report_reason not null,
  details          text,
  status           report_status not null default 'open',
  resolution_notes text,
  created_at       timestamptz not null default now(),
  resolved_at      timestamptz,
  constraint reports_details_length check (details is null or char_length(details) <= 2000)
);

create table if not exists audit_logs (
  id          uuid primary key default gen_random_uuid(),
  actor_id    uuid references profiles (user_id) on delete set null,
  action      text not null,
  entity_type text not null,
  entity_id   uuid,
  diff        jsonb,
  request_id  text,
  created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- updated_at triggers
-- ---------------------------------------------------------------------------

do $$
declare
  target text;
begin
  foreach target in array array[
    'users', 'profiles', 'design_systems', 'resources', 'collections', 'submissions'
  ]
  loop
    execute format('drop trigger if exists %I_touch on %I', target, target);
    execute format(
      'create trigger %I_touch before update on %I for each row execute function app.touch_updated_at()',
      target, target
    );
  end loop;
end
$$;
