import { readFile, stat } from "node:fs/promises";
import { basename, join, resolve } from "node:path";

import type { RegistryItem } from "@openui/types";
import { assertSafeRelativePath, explainUnsafePath, notFound, OpenUIError } from "@openui/utils";
import { sha256Hex } from "@openui/utils/node";

import { ALLOWED_FILE_EXTENSIONS, REQUIRED_ITEM_FILES } from "../constants.js";

import { formatZodError, registryItemSchema } from "../schemas.js";
import { parseDesignMarkdown, type ParsedDesignMarkdown } from "../design-md.js";

/** Files that travel with an item but are never installed into a project. */
export const AUXILIARY_FILES = [
  // The item manifest is metadata about the item, never an installable file.
  "registry.json",
  "README.md",
  "readme.md",
  "design.md",
  "demo.tsx",
  "demo.ts",
  "screenshot.webp",
  "screenshot.png",
  "screenshot.svg",
  "preview.webp",
  "preview.png",
  "preview.svg",
  "LICENSE",
  "LICENCE",
] as const;

/** Preview image candidates, in order of preference. Generated by `pnpm generate:og`. */
export const PREVIEW_FILE_CANDIDATES = [
  "screenshot.webp",
  "screenshot.png",
  "screenshot.svg",
  "preview.webp",
  "preview.png",
  "preview.svg",
] as const;

export const BINARY_EXTENSIONS = new Set([".png", ".webp"]);

export interface LoadedFile {
  /** Path as declared in `registry.json`, relative to the item directory. */
  path: string;
  absolutePath: string;
  content: string;
  contentHash: string;
  sizeBytes: number;
  isBinary: boolean;
}

export interface LoadedRegistryItem {
  /** Directory name; must equal `item.name`. */
  directoryName: string;
  directory: string;
  item: RegistryItem;
  files: LoadedFile[];
  readme: string | null;
  designMarkdown: string | null;
  designRules: ParsedDesignMarkdown | null;
  demoSource: string | null;
  screenshotPath: string | null;
  /** Every file present on disk, relative and posix-normalised. */
  allFiles: string[];
}

export function readRegistryItemJson(raw: unknown, sourcePath: string): RegistryItem {
  const result = registryItemSchema.safeParse(raw);
  if (!result.success) {
    throw new OpenUIError("registry_schema_invalid", `Invalid registry.json at ${sourcePath}.`, {
      details: formatZodError(result.error),
    });
  }
  return result.data as unknown as RegistryItem;
}

async function readTextOrNull(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf8");
  } catch {
    return null;
  }
}

async function firstExisting(paths: string[]): Promise<string | null> {
  for (const path of paths) {
    try {
      const info = await stat(path);
      if (info.isFile()) return path;
    } catch {
      /* keep looking */
    }
  }
  return null;
}

/**
 * Reads one registry item directory.
 *
 * The loader is intentionally strict about paths: every declared file is
 * re-validated even though the schema already checked it, because the loader is
 * also used on artefacts fetched from a remote registry, where the schema may
 * have been produced by an older (or hostile) build.
 */
export async function loadRegistryItem(itemDir: string): Promise<LoadedRegistryItem> {
  const directory = resolve(itemDir);
  const { readdir } = await import("node:fs/promises");

  let raw: string;
  try {
    raw = await readFile(join(directory, "registry.json"), "utf8");
  } catch (error) {
    throw notFound(`No registry.json found in ${basename(directory)}.`, { cause: error });
  }

  let parsedJson: unknown;
  try {
    parsedJson = JSON.parse(raw);
  } catch (error) {
    throw new OpenUIError("registry_schema_invalid", "registry.json is not valid JSON.", {
      cause: error,
    });
  }

  const item = readRegistryItemJson(parsedJson, join(directory, "registry.json"));

  const files: LoadedFile[] = [];
  for (const file of item.files) {
    const reason = explainUnsafePath(file.path, { allowedExtensions: ALLOWED_FILE_EXTENSIONS });
    if (reason) {
      throw new OpenUIError("invalid_registry_path", `Invalid path "${file.path}": ${reason}`);
    }
    const safePath = assertSafeRelativePath(file.path);
    const absolutePath = resolve(directory, safePath);
    const extension = safePath.slice(safePath.lastIndexOf(".")).toLowerCase();
    const isBinary = BINARY_EXTENSIONS.has(extension);

    let buffer: Buffer;
    let info;
    try {
      buffer = await readFile(absolutePath);
      info = await stat(absolutePath);
    } catch (error) {
      throw notFound(`Listed file "${file.path}" is missing from the item directory.`, { cause: error });
    }

    files.push({
      path: safePath,
      absolutePath,
      content: isBinary ? buffer.toString("base64") : buffer.toString("utf8"),
      contentHash: sha256Hex(buffer),
      sizeBytes: info.size,
      isBinary,
    });
  }

  const entries = await readdir(directory, { withFileTypes: true });
  const allFiles = entries
    .filter((entry) => entry.isFile())
    .map((entry) => entry.name)
    .sort();

  const readmePath = await firstExisting([
    join(directory, REQUIRED_ITEM_FILES[1]),
    join(directory, "readme.md"),
  ]);
  const readme = readmePath ? await readTextOrNull(readmePath) : null;

  const designMarkdown = await readTextOrNull(join(directory, "design.md"));
  const demoPath = await firstExisting([join(directory, "demo.tsx"), join(directory, "demo.ts")]);
  const demoSource = demoPath ? await readTextOrNull(demoPath) : null;
  const screenshotPath = await firstExisting(
    PREVIEW_FILE_CANDIDATES.map((file) => join(directory, file)),
  );

  return {
    directoryName: basename(directory),
    directory,
    item,
    files,
    readme,
    designMarkdown,
    designRules: designMarkdown ? parseDesignMarkdown(designMarkdown) : null,
    demoSource,
    screenshotPath,
    allFiles,
  };
}
