#!/usr/bin/env tsx
/**
 * `pnpm generate:mount-tests`
 *
 * Emits `apps/web/src/generated/mount-tests.generated.test.tsx`: one test case
 * per previewable registry demo, each importing the demo **statically** and
 * mounting it with the real React renderer in jsdom.
 *
 * Static imports are the point: a broken relative import, a hook misuse or a
 * missing export fails this file *with the resource's name*, which is exactly
 * the "broken published resource" signal the contract requires.
 */
import { writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";

import { discoverItemDirectories, loadRegistryItem } from "@openui/registry-schema/node";

import { REGISTRY_ROOT, REPO_ROOT } from "./lib/paths.js";

const DEMO_REQUIRED = new Set([
  "registry:component",
  "registry:text",
  "registry:motion",
  "registry:interaction",
  "registry:background",
  "registry:layout",
  "registry:section",
  "registry:block",
  "registry:pattern",
  "registry:template",
]);

const directories = await discoverItemDirectories(REGISTRY_ROOT);
const cases: string[] = [];
const imports: string[] = [];

for (const directory of directories) {
  const loaded = await loadRegistryItem(directory);
  if (!DEMO_REQUIRED.has(loaded.item.type) || !loaded.demoSource) continue;

  const relative = directory
    .replace(REGISTRY_ROOT + "/", "")
    .replace(/[/\\]/g, "/")
    .replace("/default/", "/");

  // The registry's own alias convention, mapped in apps/web/vite.config.ts.
  const alias = `@registry/${relative}`;
  imports.push(`import ${ident(loaded.item.name)} from "${alias}/demo";`);
  cases.push(`  it("mounts ${loaded.item.name}", async () => {
    const { createRoot } = await import("react-dom/client");
    const { act } = await import("react");
    const container = document.createElement("div");
    document.body.appendChild(container);
    const root = createRoot(container);
    await act(async () => root.render(React.createElement(${ident(loaded.item.name)})));
    expect(container.innerHTML).not.toBe("");
    await act(async () => root.unmount());
    container.remove();
  });`);
}

function ident(name: string): string {
  return (
    "Demo_" +
    name
      .split("-")
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join("")
  );
}

const output = `/**
 * GENERATED by pnpm generate:mount-tests — do not edit.
 *
 * Mounts every previewable registry demo with the real renderer. A resource
 * that throws at import or at mount fails here with its own name.
 */
import React from "react";
import { describe, expect, it } from "vitest";

${imports.join("\n")}

describe("registry demo mounts", () => {
${cases.join("\n\n")}
});
`;

const target = join(REPO_ROOT, "apps/web/src/generated/mount-tests.generated.test.tsx");
await mkdir(dirname(target), { recursive: true });
await writeFile(target, output, "utf8");

process.stdout.write(`Generated ${cases.length} mount tests → ${target.replace(REPO_ROOT + "/", "")}\n`);
